//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interfejspro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzet
    {
        public int sprzet_ID { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public byte[] Zdjęcie { get; set; }
    }
}
